apple = "I like to eat apples."
bat = "I swing my bat when I play baseball."
car = "I like to watch cars race. Do you?"
dog = "Dogs go woof woof!"
eat = "I don't like vegetables, but I eat them anyway."
fan = "Fans keep me cool in the summer."
gum = "Did you know you can blow bubbles with gum?"
hat = "Farmers wear straw hats to keep the sun out of their eyes."
igloo = "An igloo is a house made of snow. Isn't that cool?"
jump = "Sometimes, when I'm excited, I jump up and down!"
pear = "Pears are very sweet."
you = "You are very special!"
